version: '3.9'

services:
  
  # Database container
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password1!"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - companyapi-network
  
  # Run initial scripts container
  sql-server-cmd:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: sql-server-cmd
    command: /bin/bash -c '/opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P Password1! -i /dbinit.sql'
    restart: on-failure
    networks:
      - companyapi-network
    depends_on: 
      - sql-server
  
  #backend container
  web-api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: dotnet-api
    ports:
      - "5055:8080"
    networks:
      - companyapi-network
    depends_on: 
      - sql-server
  
  # Aplicação Angular 16
  web-app:
    build:
      context: ./src/CompanyApp.WebUI
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:80"
    networks:
      - companyapi-network
    depends_on: 
      - web-api


volumes:
  sqlvolume:

networks:
  companyapi-network:
    driver: bridge