name: Build and Coverage

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Adjust to your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: ./CompanyApi.Test # Adjust to your test project path

    - name: Publish to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./CompanyApi.Test/coverage/*/coverage.cobertura.xml # Wildcard for GUID folder
        flag-name: unit-tests
        parallel: false
